/* @refresh reload */
/**
 * Don't forget the line above for HMR!
 * 
 * Note: for some reason HMR breaks if you change .stories file,
 * however reloading the page fixes this issue
 */

import { render, createComponent } from "solid-js/web";
import { UIProvider } from '../src/Provider'

let disposeStory;

export const decorators = [
  (Story) => {
    disposeStory?.();

    const Provider = createComponent(UIProvider, {
      enableCssReset: true,
      config: {
        fonts: {
          default: "Nunito",
        },
      }
    });

    const solidRoot = Provider();

    disposeStory = render(Story, solidRoot);

    return solidRoot;
  },
];

/** Autogenerated by Storybook */
export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
};